// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://coaxwkvzkacazkibocuz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvYXh3a3Z6a2FjYXpraWJvY3V6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NTY2OTUsImV4cCI6MjA3MjMzMjY5NX0.Wi6g2ajkwMh0Cg6kNahc615nHbh5ispq1JguDS5WDlc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});